import type { Metadata } from "next";
import { PropsWithChildren } from "react";
import { QueryProvider } from "@/lib/react-query";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
    return (
        <html lang="en">
            <body>
                <QueryProvider>
                    <main>
                        { children }
                    </main>
                    <Toaster theme={"light"} position={"top-center"} />
                </QueryProvider>
            </body>
        </html>
    );
}
